pipelineName: docs-merge-pipeline
repo: pingcap/docs
defaultRef: master
triggers:
  push:
      onBranch:
      - "master"
      - "release-7.3"
      - "release-7.2"
      - "release-7.1"
      - "release-7.0"
      - "release-6.6"
      - "release-6.5"
      - "release-6.1"
      - "release-5.4"
      - "release-5.3"
      - "release-5.2"
      - "release-5.1"
      - "release-5.0"
      - "release-4.0"
      - "release-3.0"
tasks:
    - taskName: "docs-build-pdf"
      checkerName: "common-check"
      params:
        shellScript: |
          sudo pip3 install boto3
          sudo pip3 install awscli
          printf "%s\n" ${AWS_ACCESS_KEY} ${AWS_SECRET_KEY} ${AWS_REGION} "json" | aws configure
          find -name '*.md' | xargs -d '\n' grep -P '\t' && exit 1
          python3 scripts/merge_by_toc.py
          scripts/generate_pdf.sh
          if [ "${TARGET_BRANCH}" = "master" ]; then
            python3 scripts/upload.py output.pdf tidb-dev-en-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-7.1" ]; then
            python3 scripts/merge_by_toc.py TOC-tidb-cloud.md doc_cloud.md tidb-cloud; scripts/generate_cloud_pdf.sh;
            python3 scripts/upload.py output_cloud.pdf tidbcloud-en-manual.pdf;
            python3 scripts/upload.py output.pdf tidb-stable-en-manual.pdf;
          elif case "${TARGET_BRANCH}" in release-*) ;; *) false;; esac; then
            python3 scripts/upload.py output.pdf tidb-v${TARGET_BRANCH##*-}-en-manual.pdf;
          fi
      credentials:
        - jenkinsID: docs-cn-aws-ak
          key: AWS_ACCESS_KEY
        - jenkinsID: docs-cn-aws-sk
          key: AWS_SECRET_KEY
        - jenkinsID: docs-cn-aws-region
          key: AWS_REGION
        - jenkinsID: docs-cn-aws-bn
          key: AWS_BUCKET_NAME
        - jenkinsID: docs-cn-qiniu-ak
          key: QINIU_ACCESS_KEY
        - jenkinsID: docs-cn-qiniu-sk
          key: QINIU_SECRET_KEY
        - jenkinsID: docs-cn-qiniu-bn
          key: QINIU_BUCKET_NAME
      image: "hub.pingcap.net/jenkins/docs-cn-checker:v0.0.1"
      resources:
          requests:
              memory: "2000Mi"
              cpu: "500m"
          limits:
              memory: "4000Mi"
              cpu: "1000m"
